name: Deploy bot
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/nodeapps/illuminatibottiv2 # navigate into the folder
            rm -rf build # Delete current build
            git pull origin master # clone the repo
            npm install # install dependencies
            tsc --build --verbose # build typescript
            rm -rf src # Delete source folder
            pm2 start ecosystem.config.js # start as a background service.
